* Cherian et al (2021) Off-equatorial deep-cycle turbulence forced by Tropical Instability Waves in the equatorial Pacific

*Paper DOI*: XXXX  ||  *Zenodo DOI*: [[https://dx.doi.org/10.5281/zenodo.4535984][10.5281/zenodo.4535984]]

This repository provides code to reproduce Figures 2-12 in [[https://github.com/dcherian/cherian-2021-tiw-dcl/blob/master/dcl-paper-clean.ipynb][dcl-paper-clean.ipynb]]. Reproduction requires two publicly available datasets hosted on NCAR's [[https://dashrepo.ucar.edu][Digital Asset Services Hub (DASH)]] repository.

1. [[https://dx.doi.org/10.5065/6qa0-v481][doi:10.5065/6qa0-v481]]: daily averages for much of the domain, and 4-hourly output along latitudinal sections at longitudes 110째W, 125째W, 140째W, and 155째W.
2. [[https://dx.doi.org/10.5065/3kb5-g350][doi:10.5065/3kb5-g350]]: hourly fields for the particular TIW that is the focus of this paper.

** Acknowledgments
This work was funded by National Oceanic and Atmospheric Administration Contract
NA18OAR4310408 from the Climate Program Office. We would like to acknowledge high-performance computing support from Cheyenne ([[https://dx.doi.org/10.5065/D6RX99HX][doi:10.5065/D6RX99HX]]) provided by NCAR's Computational and Information Systems Laboratory, sponsored by the National Science Foundation. This material is based upon work supported by the National Center for Atmospheric Research, which is a major facility sponsored by the National Science Foundation under Cooperative Agreement No. 1852977.
